// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: report_processed.proto

package forwarder

import (
	monitoring "github.com/smartcontractkit/capabilities/libs/monitoring"
	common "github.com/smartcontractkit/chainlink-framework/capabilities/writetarget/monitoring/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The on-chain ReportProcessed event which is extracted from the tx/event data or
// the write-target WriteConfirmed event, after a write was confirmed (@see message: platform.write-target.WriteConfirmed).
type ReportProcessed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event data
	Receiver            string                       `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	WorkflowExecutionId string                       `protobuf:"bytes,2,opt,name=workflow_execution_id,json=workflowExecutionId,proto3" json:"workflow_execution_id,omitempty"` // bytes as hex string for readability
	ReportId            uint32                       `protobuf:"varint,3,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Success             bool                         `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	BlockData           *common.BlockData            `protobuf:"bytes,6,opt,name=block_data,json=blockData,proto3" json:"block_data,omitempty"`
	TransactionData     *common.TransactionData      `protobuf:"bytes,10,opt,name=transaction_data,json=transactionData,proto3" json:"transaction_data,omitempty"`
	ExecutionContext    *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReportProcessed) Reset() {
	*x = ReportProcessed{}
	mi := &file_report_processed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProcessed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProcessed) ProtoMessage() {}

func (x *ReportProcessed) ProtoReflect() protoreflect.Message {
	mi := &file_report_processed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProcessed.ProtoReflect.Descriptor instead.
func (*ReportProcessed) Descriptor() ([]byte, []int) {
	return file_report_processed_proto_rawDescGZIP(), []int{0}
}

func (x *ReportProcessed) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *ReportProcessed) GetWorkflowExecutionId() string {
	if x != nil {
		return x.WorkflowExecutionId
	}
	return ""
}

func (x *ReportProcessed) GetReportId() uint32 {
	if x != nil {
		return x.ReportId
	}
	return 0
}

func (x *ReportProcessed) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportProcessed) GetBlockData() *common.BlockData {
	if x != nil {
		return x.BlockData
	}
	return nil
}

func (x *ReportProcessed) GetTransactionData() *common.TransactionData {
	if x != nil {
		return x.TransactionData
	}
	return nil
}

func (x *ReportProcessed) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

var File_report_processed_proto protoreflect.FileDescriptor

const file_report_processed_proto_rawDesc = "" +
	"\n" +
	"\x16report_processed.proto\x12\x1bplatform.on_chain.forwarder\x1a\"monitoring/execution_context.proto\x1a>capabilities/writetarget/monitoring/pb/common/block_data.proto\x1aDcapabilities/writetarget/monitoring/pb/common/transaction_data.proto\"\xd9\x02\n" +
	"\x0fReportProcessed\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x122\n" +
	"\x15workflow_execution_id\x18\x02 \x01(\tR\x13workflowExecutionId\x12\x1b\n" +
	"\treport_id\x18\x03 \x01(\rR\breportId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x120\n" +
	"\n" +
	"block_data\x18\x06 \x01(\v2\x11.common.BlockDataR\tblockData\x12B\n" +
	"\x10transaction_data\x18\n" +
	" \x01(\v2\x17.common.TransactionDataR\x0ftransactionData\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContextB~Z|github.com/smartcontractkit/chainlink-framework/capabilities/writetarget/monitoring/pb/platform/on-chain/forwarder;forwarderb\x06proto3"

var (
	file_report_processed_proto_rawDescOnce sync.Once
	file_report_processed_proto_rawDescData []byte
)

func file_report_processed_proto_rawDescGZIP() []byte {
	file_report_processed_proto_rawDescOnce.Do(func() {
		file_report_processed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_processed_proto_rawDesc), len(file_report_processed_proto_rawDesc)))
	})
	return file_report_processed_proto_rawDescData
}

var file_report_processed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_report_processed_proto_goTypes = []any{
	(*ReportProcessed)(nil),             // 0: platform.on_chain.forwarder.ReportProcessed
	(*common.BlockData)(nil),            // 1: common.BlockData
	(*common.TransactionData)(nil),      // 2: common.TransactionData
	(*monitoring.ExecutionContext)(nil), // 3: monitoring.ExecutionContext
}
var file_report_processed_proto_depIdxs = []int32{
	1, // 0: platform.on_chain.forwarder.ReportProcessed.block_data:type_name -> common.BlockData
	2, // 1: platform.on_chain.forwarder.ReportProcessed.transaction_data:type_name -> common.TransactionData
	3, // 2: platform.on_chain.forwarder.ReportProcessed.execution_context:type_name -> monitoring.ExecutionContext
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_report_processed_proto_init() }
func file_report_processed_proto_init() {
	if File_report_processed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_processed_proto_rawDesc), len(file_report_processed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_report_processed_proto_goTypes,
		DependencyIndexes: file_report_processed_proto_depIdxs,
		MessageInfos:      file_report_processed_proto_msgTypes,
	}.Build()
	File_report_processed_proto = out.File
	file_report_processed_proto_goTypes = nil
	file_report_processed_proto_depIdxs = nil
}
