// Code generated by mockery v2.53.0. DO NOT EDIT.

package multinode

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockFinalizedStateChecker is an autogenerated mock type for the FinalizedStateChecker type
type mockFinalizedStateChecker struct {
	mock.Mock
}

type mockFinalizedStateChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFinalizedStateChecker) EXPECT() *mockFinalizedStateChecker_Expecter {
	return &mockFinalizedStateChecker_Expecter{mock: &_m.Mock}
}

// CheckFinalizedStateAvailability provides a mock function with given fields: ctx
func (_m *mockFinalizedStateChecker) CheckFinalizedStateAvailability(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckFinalizedStateAvailability")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockFinalizedStateChecker_CheckFinalizedStateAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckFinalizedStateAvailability'
type mockFinalizedStateChecker_CheckFinalizedStateAvailability_Call struct {
	*mock.Call
}

// CheckFinalizedStateAvailability is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockFinalizedStateChecker_Expecter) CheckFinalizedStateAvailability(ctx interface{}) *mockFinalizedStateChecker_CheckFinalizedStateAvailability_Call {
	return &mockFinalizedStateChecker_CheckFinalizedStateAvailability_Call{Call: _e.mock.On("CheckFinalizedStateAvailability", ctx)}
}

func (_c *mockFinalizedStateChecker_CheckFinalizedStateAvailability_Call) Run(run func(ctx context.Context)) *mockFinalizedStateChecker_CheckFinalizedStateAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockFinalizedStateChecker_CheckFinalizedStateAvailability_Call) Return(_a0 error) *mockFinalizedStateChecker_CheckFinalizedStateAvailability_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockFinalizedStateChecker_CheckFinalizedStateAvailability_Call) RunAndReturn(run func(context.Context) error) *mockFinalizedStateChecker_CheckFinalizedStateAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// newMockFinalizedStateChecker creates a new instance of mockFinalizedStateChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFinalizedStateChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFinalizedStateChecker {
	mock := &mockFinalizedStateChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
