// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// ProductSpecificProcessor is an autogenerated mock type for the ProductSpecificProcessor type
type ProductSpecificProcessor struct {
	mock.Mock
}

type ProductSpecificProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductSpecificProcessor) EXPECT() *ProductSpecificProcessor_Expecter {
	return &ProductSpecificProcessor_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *ProductSpecificProcessor) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ProductSpecificProcessor_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type ProductSpecificProcessor_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *ProductSpecificProcessor_Expecter) Name() *ProductSpecificProcessor_Name_Call {
	return &ProductSpecificProcessor_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *ProductSpecificProcessor_Name_Call) Run(run func()) *ProductSpecificProcessor_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProductSpecificProcessor_Name_Call) Return(_a0 string) *ProductSpecificProcessor_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductSpecificProcessor_Name_Call) RunAndReturn(run func() string) *ProductSpecificProcessor_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Process provides a mock function with given fields: ctx, m, attrKVs
func (_m *ProductSpecificProcessor) Process(ctx context.Context, m protoreflect.ProtoMessage, attrKVs ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, m)
	_ca = append(_ca, attrKVs...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage, ...interface{}) error); ok {
		r0 = rf(ctx, m, attrKVs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductSpecificProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type ProductSpecificProcessor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - m protoreflect.ProtoMessage
//   - attrKVs ...interface{}
func (_e *ProductSpecificProcessor_Expecter) Process(ctx interface{}, m interface{}, attrKVs ...interface{}) *ProductSpecificProcessor_Process_Call {
	return &ProductSpecificProcessor_Process_Call{Call: _e.mock.On("Process",
		append([]interface{}{ctx, m}, attrKVs...)...)}
}

func (_c *ProductSpecificProcessor_Process_Call) Run(run func(ctx context.Context, m protoreflect.ProtoMessage, attrKVs ...interface{})) *ProductSpecificProcessor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(protoreflect.ProtoMessage), variadicArgs...)
	})
	return _c
}

func (_c *ProductSpecificProcessor_Process_Call) Return(_a0 error) *ProductSpecificProcessor_Process_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductSpecificProcessor_Process_Call) RunAndReturn(run func(context.Context, protoreflect.ProtoMessage, ...interface{}) error) *ProductSpecificProcessor_Process_Call {
	_c.Call.Return(run)
	return _c
}

// NewProductSpecificProcessor creates a new instance of ProductSpecificProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductSpecificProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductSpecificProcessor {
	mock := &ProductSpecificProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
