// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// ProtoEmitter is an autogenerated mock type for the ProtoEmitter type
type ProtoEmitter struct {
	mock.Mock
}

type ProtoEmitter_Expecter struct {
	mock *mock.Mock
}

func (_m *ProtoEmitter) EXPECT() *ProtoEmitter_Expecter {
	return &ProtoEmitter_Expecter{mock: &_m.Mock}
}

// Emit provides a mock function with given fields: ctx, m, attrKVs
func (_m *ProtoEmitter) Emit(ctx context.Context, m protoreflect.ProtoMessage, attrKVs ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, m)
	_ca = append(_ca, attrKVs...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Emit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage, ...interface{}) error); ok {
		r0 = rf(ctx, m, attrKVs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProtoEmitter_Emit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Emit'
type ProtoEmitter_Emit_Call struct {
	*mock.Call
}

// Emit is a helper method to define mock.On call
//   - ctx context.Context
//   - m protoreflect.ProtoMessage
//   - attrKVs ...interface{}
func (_e *ProtoEmitter_Expecter) Emit(ctx interface{}, m interface{}, attrKVs ...interface{}) *ProtoEmitter_Emit_Call {
	return &ProtoEmitter_Emit_Call{Call: _e.mock.On("Emit",
		append([]interface{}{ctx, m}, attrKVs...)...)}
}

func (_c *ProtoEmitter_Emit_Call) Run(run func(ctx context.Context, m protoreflect.ProtoMessage, attrKVs ...interface{})) *ProtoEmitter_Emit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(protoreflect.ProtoMessage), variadicArgs...)
	})
	return _c
}

func (_c *ProtoEmitter_Emit_Call) Return(_a0 error) *ProtoEmitter_Emit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProtoEmitter_Emit_Call) RunAndReturn(run func(context.Context, protoreflect.ProtoMessage, ...interface{}) error) *ProtoEmitter_Emit_Call {
	_c.Call.Return(run)
	return _c
}

// EmitWithLog provides a mock function with given fields: ctx, m, attrKVs
func (_m *ProtoEmitter) EmitWithLog(ctx context.Context, m protoreflect.ProtoMessage, attrKVs ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, m)
	_ca = append(_ca, attrKVs...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EmitWithLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage, ...interface{}) error); ok {
		r0 = rf(ctx, m, attrKVs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProtoEmitter_EmitWithLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmitWithLog'
type ProtoEmitter_EmitWithLog_Call struct {
	*mock.Call
}

// EmitWithLog is a helper method to define mock.On call
//   - ctx context.Context
//   - m protoreflect.ProtoMessage
//   - attrKVs ...interface{}
func (_e *ProtoEmitter_Expecter) EmitWithLog(ctx interface{}, m interface{}, attrKVs ...interface{}) *ProtoEmitter_EmitWithLog_Call {
	return &ProtoEmitter_EmitWithLog_Call{Call: _e.mock.On("EmitWithLog",
		append([]interface{}{ctx, m}, attrKVs...)...)}
}

func (_c *ProtoEmitter_EmitWithLog_Call) Run(run func(ctx context.Context, m protoreflect.ProtoMessage, attrKVs ...interface{})) *ProtoEmitter_EmitWithLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(protoreflect.ProtoMessage), variadicArgs...)
	})
	return _c
}

func (_c *ProtoEmitter_EmitWithLog_Call) Return(_a0 error) *ProtoEmitter_EmitWithLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProtoEmitter_EmitWithLog_Call) RunAndReturn(run func(context.Context, protoreflect.ProtoMessage, ...interface{}) error) *ProtoEmitter_EmitWithLog_Call {
	_c.Call.Return(run)
	return _c
}

// NewProtoEmitter creates a new instance of ProtoEmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProtoEmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProtoEmitter {
	mock := &ProtoEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
