// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: block_data.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [Block Data]
type BlockData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Head data - when was the event produced on-chain
	BlockHash      string `protobuf:"bytes,6,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockHeight    string `protobuf:"bytes,7,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	BlockTimestamp uint64 `protobuf:"varint,8,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockData) Reset() {
	*x = BlockData{}
	mi := &file_block_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockData) ProtoMessage() {}

func (x *BlockData) ProtoReflect() protoreflect.Message {
	mi := &file_block_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockData.ProtoReflect.Descriptor instead.
func (*BlockData) Descriptor() ([]byte, []int) {
	return file_block_data_proto_rawDescGZIP(), []int{0}
}

func (x *BlockData) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BlockData) GetBlockHeight() string {
	if x != nil {
		return x.BlockHeight
	}
	return ""
}

func (x *BlockData) GetBlockTimestamp() uint64 {
	if x != nil {
		return x.BlockTimestamp
	}
	return 0
}

var File_block_data_proto protoreflect.FileDescriptor

const file_block_data_proto_rawDesc = "" +
	"\n" +
	"\x10block_data.proto\x12\x06common\"v\n" +
	"\tBlockData\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x06 \x01(\tR\tblockHash\x12!\n" +
	"\fblock_height\x18\a \x01(\tR\vblockHeight\x12'\n" +
	"\x0fblock_timestamp\x18\b \x01(\x04R\x0eblockTimestampBfZdgithub.com/smartcontractkit/chainlink-framework/capabilities/writetarget/monitoring/pb/common;commonb\x06proto3"

var (
	file_block_data_proto_rawDescOnce sync.Once
	file_block_data_proto_rawDescData []byte
)

func file_block_data_proto_rawDescGZIP() []byte {
	file_block_data_proto_rawDescOnce.Do(func() {
		file_block_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_data_proto_rawDesc), len(file_block_data_proto_rawDesc)))
	})
	return file_block_data_proto_rawDescData
}

var file_block_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_block_data_proto_goTypes = []any{
	(*BlockData)(nil), // 0: common.BlockData
}
var file_block_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_block_data_proto_init() }
func file_block_data_proto_init() {
	if File_block_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_data_proto_rawDesc), len(file_block_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_data_proto_goTypes,
		DependencyIndexes: file_block_data_proto_depIdxs,
		MessageInfos:      file_block_data_proto_msgTypes,
	}.Build()
	File_block_data_proto = out.File
	file_block_data_proto_goTypes = nil
	file_block_data_proto_depIdxs = nil
}
