// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: transaction_data.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [Transaction Data]
type TransactionData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction data - info about the tx that mained the event (optional)
	TxId          string `protobuf:"bytes,10,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"` // TXM ref
	TxHash        string `protobuf:"bytes,11,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TxSender      string `protobuf:"bytes,12,opt,name=tx_sender,json=txSender,proto3" json:"tx_sender,omitempty"`
	TxReceiver    string `protobuf:"bytes,13,opt,name=tx_receiver,json=txReceiver,proto3" json:"tx_receiver,omitempty"`
	TxStatus      string `protobuf:"bytes,14,opt,name=tx_status,json=txStatus,proto3" json:"tx_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionData) Reset() {
	*x = TransactionData{}
	mi := &file_transaction_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionData) ProtoMessage() {}

func (x *TransactionData) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionData.ProtoReflect.Descriptor instead.
func (*TransactionData) Descriptor() ([]byte, []int) {
	return file_transaction_data_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionData) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TransactionData) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransactionData) GetTxSender() string {
	if x != nil {
		return x.TxSender
	}
	return ""
}

func (x *TransactionData) GetTxReceiver() string {
	if x != nil {
		return x.TxReceiver
	}
	return ""
}

func (x *TransactionData) GetTxStatus() string {
	if x != nil {
		return x.TxStatus
	}
	return ""
}

var File_transaction_data_proto protoreflect.FileDescriptor

const file_transaction_data_proto_rawDesc = "" +
	"\n" +
	"\x16transaction_data.proto\x12\x06common\"\x9a\x01\n" +
	"\x0fTransactionData\x12\x13\n" +
	"\x05tx_id\x18\n" +
	" \x01(\tR\x04txId\x12\x17\n" +
	"\atx_hash\x18\v \x01(\tR\x06txHash\x12\x1b\n" +
	"\ttx_sender\x18\f \x01(\tR\btxSender\x12\x1f\n" +
	"\vtx_receiver\x18\r \x01(\tR\n" +
	"txReceiver\x12\x1b\n" +
	"\ttx_status\x18\x0e \x01(\tR\btxStatusBfZdgithub.com/smartcontractkit/chainlink-framework/capabilities/writetarget/monitoring/pb/common;commonb\x06proto3"

var (
	file_transaction_data_proto_rawDescOnce sync.Once
	file_transaction_data_proto_rawDescData []byte
)

func file_transaction_data_proto_rawDescGZIP() []byte {
	file_transaction_data_proto_rawDescOnce.Do(func() {
		file_transaction_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_data_proto_rawDesc), len(file_transaction_data_proto_rawDesc)))
	})
	return file_transaction_data_proto_rawDescData
}

var file_transaction_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transaction_data_proto_goTypes = []any{
	(*TransactionData)(nil), // 0: common.TransactionData
}
var file_transaction_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_data_proto_init() }
func file_transaction_data_proto_init() {
	if File_transaction_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_data_proto_rawDesc), len(file_transaction_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_data_proto_goTypes,
		DependencyIndexes: file_transaction_data_proto_depIdxs,
		MessageInfos:      file_transaction_data_proto_msgTypes,
	}.Build()
	File_transaction_data_proto = out.File
	file_transaction_data_proto_goTypes = nil
	file_transaction_data_proto_depIdxs = nil
}
