// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: write_confirmed.proto

package writetarget

import (
	common "github.com/smartcontractkit/chainlink-framework/capabilities/writetarget/monitoring/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WT confirmed the report was successfully written on-chain
type WriteConfirmed struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Node      string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Forwarder string                 `protobuf:"bytes,2,opt,name=forwarder,proto3" json:"forwarder,omitempty"`
	Receiver  string                 `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// Report Info
	ReportId      uint32 `protobuf:"varint,4,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	ReportContext []byte `protobuf:"bytes,5,opt,name=report_context,json=reportContext,proto3" json:"report_context,omitempty"`
	Report        []byte `protobuf:"bytes,6,opt,name=report,proto3" json:"report,omitempty"`
	SignersNum    uint32 `protobuf:"varint,7,opt,name=signers_num,json=signersNum,proto3" json:"signers_num,omitempty"`
	// When was the report confirmed on-chain
	BlockData *common.BlockData `protobuf:"bytes,9,opt,name=block_data,json=blockData,proto3" json:"block_data,omitempty"`
	// Transmission Info
	Transmitter string `protobuf:"bytes,12,opt,name=transmitter,proto3" json:"transmitter,omitempty"`
	Success     bool   `protobuf:"varint,13,opt,name=success,proto3" json:"success,omitempty"` // TODO: what about EVM's TransmissionInfo parity?
	// [Execution Context]
	ExecutionContext *common.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	// encoder processor info
	MetaCapabilityProcessor string `protobuf:"bytes,21,opt,name=meta_capability_processor,json=metaCapabilityProcessor,proto3" json:"meta_capability_processor,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *WriteConfirmed) Reset() {
	*x = WriteConfirmed{}
	mi := &file_write_confirmed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConfirmed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConfirmed) ProtoMessage() {}

func (x *WriteConfirmed) ProtoReflect() protoreflect.Message {
	mi := &file_write_confirmed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConfirmed.ProtoReflect.Descriptor instead.
func (*WriteConfirmed) Descriptor() ([]byte, []int) {
	return file_write_confirmed_proto_rawDescGZIP(), []int{0}
}

func (x *WriteConfirmed) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *WriteConfirmed) GetForwarder() string {
	if x != nil {
		return x.Forwarder
	}
	return ""
}

func (x *WriteConfirmed) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *WriteConfirmed) GetReportId() uint32 {
	if x != nil {
		return x.ReportId
	}
	return 0
}

func (x *WriteConfirmed) GetReportContext() []byte {
	if x != nil {
		return x.ReportContext
	}
	return nil
}

func (x *WriteConfirmed) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *WriteConfirmed) GetSignersNum() uint32 {
	if x != nil {
		return x.SignersNum
	}
	return 0
}

func (x *WriteConfirmed) GetBlockData() *common.BlockData {
	if x != nil {
		return x.BlockData
	}
	return nil
}

func (x *WriteConfirmed) GetTransmitter() string {
	if x != nil {
		return x.Transmitter
	}
	return ""
}

func (x *WriteConfirmed) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteConfirmed) GetExecutionContext() *common.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

func (x *WriteConfirmed) GetMetaCapabilityProcessor() string {
	if x != nil {
		return x.MetaCapabilityProcessor
	}
	return ""
}

var File_write_confirmed_proto protoreflect.FileDescriptor

const file_write_confirmed_proto_rawDesc = "" +
	"\n" +
	"\x15write_confirmed.proto\x12\x15platform.write_target\x1aEcapabilities/writetarget/monitoring/pb/common/execution_context.proto\x1a>capabilities/writetarget/monitoring/pb/common/block_data.proto\"\xcc\x03\n" +
	"\x0eWriteConfirmed\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x1c\n" +
	"\tforwarder\x18\x02 \x01(\tR\tforwarder\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver\x12\x1b\n" +
	"\treport_id\x18\x04 \x01(\rR\breportId\x12%\n" +
	"\x0ereport_context\x18\x05 \x01(\fR\rreportContext\x12\x16\n" +
	"\x06report\x18\x06 \x01(\fR\x06report\x12\x1f\n" +
	"\vsigners_num\x18\a \x01(\rR\n" +
	"signersNum\x120\n" +
	"\n" +
	"block_data\x18\t \x01(\v2\x11.common.BlockDataR\tblockData\x12 \n" +
	"\vtransmitter\x18\f \x01(\tR\vtransmitter\x12\x18\n" +
	"\asuccess\x18\r \x01(\bR\asuccess\x12E\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x18.common.ExecutionContextR\x10executionContext\x12:\n" +
	"\x19meta_capability_processor\x18\x15 \x01(\tR\x17metaCapabilityProcessorBmZkgithub.com/smartcontractkit/chainlink-framework/capabilities/writetarget/monitoring/pb/platform;writetargetb\x06proto3"

var (
	file_write_confirmed_proto_rawDescOnce sync.Once
	file_write_confirmed_proto_rawDescData []byte
)

func file_write_confirmed_proto_rawDescGZIP() []byte {
	file_write_confirmed_proto_rawDescOnce.Do(func() {
		file_write_confirmed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_write_confirmed_proto_rawDesc), len(file_write_confirmed_proto_rawDesc)))
	})
	return file_write_confirmed_proto_rawDescData
}

var file_write_confirmed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_write_confirmed_proto_goTypes = []any{
	(*WriteConfirmed)(nil),          // 0: platform.write_target.WriteConfirmed
	(*common.BlockData)(nil),        // 1: common.BlockData
	(*common.ExecutionContext)(nil), // 2: common.ExecutionContext
}
var file_write_confirmed_proto_depIdxs = []int32{
	1, // 0: platform.write_target.WriteConfirmed.block_data:type_name -> common.BlockData
	2, // 1: platform.write_target.WriteConfirmed.execution_context:type_name -> common.ExecutionContext
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_write_confirmed_proto_init() }
func file_write_confirmed_proto_init() {
	if File_write_confirmed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_write_confirmed_proto_rawDesc), len(file_write_confirmed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_write_confirmed_proto_goTypes,
		DependencyIndexes: file_write_confirmed_proto_depIdxs,
		MessageInfos:      file_write_confirmed_proto_msgTypes,
	}.Build()
	File_write_confirmed_proto = out.File
	file_write_confirmed_proto_goTypes = nil
	file_write_confirmed_proto_depIdxs = nil
}
