// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: write_sent.proto

package writetarget

import (
	common "github.com/smartcontractkit/chainlink-framework/capabilities/writetarget/monitoring/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WT sent a transaction on-chain
//
// Notice: we publish txId (TXM ref) vs. txHash (N/A here)
type WriteSent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Node      string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Forwarder string                 `protobuf:"bytes,2,opt,name=forwarder,proto3" json:"forwarder,omitempty"`
	Receiver  string                 `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// Report Info
	ReportId uint32 `protobuf:"varint,4,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	// Transaction ID - tx reference as created by the WT, to be used for tracking TXM execution
	TxId string `protobuf:"bytes,5,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// When was the transaction submitted
	BlockData *common.BlockData `protobuf:"bytes,7,opt,name=block_data,json=blockData,proto3" json:"block_data,omitempty"`
	// [Execution Context]
	ExecutionContext *common.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteSent) Reset() {
	*x = WriteSent{}
	mi := &file_write_sent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSent) ProtoMessage() {}

func (x *WriteSent) ProtoReflect() protoreflect.Message {
	mi := &file_write_sent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSent.ProtoReflect.Descriptor instead.
func (*WriteSent) Descriptor() ([]byte, []int) {
	return file_write_sent_proto_rawDescGZIP(), []int{0}
}

func (x *WriteSent) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *WriteSent) GetForwarder() string {
	if x != nil {
		return x.Forwarder
	}
	return ""
}

func (x *WriteSent) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *WriteSent) GetReportId() uint32 {
	if x != nil {
		return x.ReportId
	}
	return 0
}

func (x *WriteSent) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *WriteSent) GetBlockData() *common.BlockData {
	if x != nil {
		return x.BlockData
	}
	return nil
}

func (x *WriteSent) GetExecutionContext() *common.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

var File_write_sent_proto protoreflect.FileDescriptor

const file_write_sent_proto_rawDesc = "" +
	"\n" +
	"\x10write_sent.proto\x12\x15platform.write_target\x1aEcapabilities/writetarget/monitoring/pb/common/execution_context.proto\x1a>capabilities/writetarget/monitoring/pb/common/block_data.proto\"\x84\x02\n" +
	"\tWriteSent\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x1c\n" +
	"\tforwarder\x18\x02 \x01(\tR\tforwarder\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver\x12\x1b\n" +
	"\treport_id\x18\x04 \x01(\rR\breportId\x12\x13\n" +
	"\x05tx_id\x18\x05 \x01(\tR\x04txId\x120\n" +
	"\n" +
	"block_data\x18\a \x01(\v2\x11.common.BlockDataR\tblockData\x12E\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x18.common.ExecutionContextR\x10executionContextBmZkgithub.com/smartcontractkit/chainlink-framework/capabilities/writetarget/monitoring/pb/platform;writetargetb\x06proto3"

var (
	file_write_sent_proto_rawDescOnce sync.Once
	file_write_sent_proto_rawDescData []byte
)

func file_write_sent_proto_rawDescGZIP() []byte {
	file_write_sent_proto_rawDescOnce.Do(func() {
		file_write_sent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_write_sent_proto_rawDesc), len(file_write_sent_proto_rawDesc)))
	})
	return file_write_sent_proto_rawDescData
}

var file_write_sent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_write_sent_proto_goTypes = []any{
	(*WriteSent)(nil),               // 0: platform.write_target.WriteSent
	(*common.BlockData)(nil),        // 1: common.BlockData
	(*common.ExecutionContext)(nil), // 2: common.ExecutionContext
}
var file_write_sent_proto_depIdxs = []int32{
	1, // 0: platform.write_target.WriteSent.block_data:type_name -> common.BlockData
	2, // 1: platform.write_target.WriteSent.execution_context:type_name -> common.ExecutionContext
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_write_sent_proto_init() }
func file_write_sent_proto_init() {
	if File_write_sent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_write_sent_proto_rawDesc), len(file_write_sent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_write_sent_proto_goTypes,
		DependencyIndexes: file_write_sent_proto_depIdxs,
		MessageInfos:      file_write_sent_proto_msgTypes,
	}.Build()
	File_write_sent_proto = out.File
	file_write_sent_proto_goTypes = nil
	file_write_sent_proto_depIdxs = nil
}
