name: Lint MultiNode

on: [push]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.19'

      - name: Lint multinode
        run: |
          cd ./multinode
          golangci-lint run
        env:
          GOLANGCI_LINT_VERSION: v1.62.2
