name: Lint MultiNode

on: [push]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run golangci-lint for multinode
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.62.2
          working-directory: ./multinode
          args: run
