name: Lint MultiNode

on: [push]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.19'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.2
        env:
          GOROOT: /usr/local/go
          GOPATH: $HOME/go
          PATH: $HOME/go/bin:/usr/local/go/bin:$PATH

      - name: Lint multinode
        run: |
          cd ./multinode
          golangci-lint run
