name: Golangci-lint

on: [pull_request]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.19'

      - name: Find Go modules
        id: find-modules
        run: |
          # Find all directories containing a go.mod file and save them as a newline-separated list
          find . -name "go.mod" -exec dirname {} \; > go_modules.txt
          echo "modules=$(cat go_modules.txt | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run golangci-lint for each module
        run: |
          failed_modules=""
          for module in ${{ steps.find-modules.outputs.modules }}; do
            echo "Running golangci-lint in $module"
            cd $module

            if ! golangci-lint run; then
              failed_modules="$failed_modules $module"
            fi

            cd -
          done

          if [ -n "$failed_modules" ]; then
            echo "The following modules failed linting:"
            echo "$failed_modules"
            exit 1
          else
            echo "All modules passed linting."
          fi
